name: mjolnir
description: Mjolnir for Dart. An API SDK building tool.
version: 0.2.0
homepage: https://github.com/vishna/mjolnir-dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.7
  equatable: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter